from ConfiguracionSolapasExtensionAulicaForm import ConfiguracionSolapasExtensionAulicaForm
from ConfiguracionSolapasAnexoForm import ConfiguracionSolapasAnexoForm
from ConfiguracionSolapasEstablecimientoForm import ConfiguracionSolapasEstablecimientoForm
