from EstadoSolicitud import EstadoSolicitud
from Solicitud import Solicitud
from SolicitudEstablecimiento import SolicitudEstablecimiento
from SolicitudEstado import SolicitudEstado
from ValidezNacional import ValidezNacional
from SolicitudAnexo import SolicitudAnexo
from InformeSolicitud import InformeSolicitud
