from Area import Area
#
from Carrera import Carrera
from CarreraEstado import CarreraEstado
from EstadoCarrera import EstadoCarrera
#
from TipoTitulo import TipoTitulo
from TituloEstado import TituloEstado
from TituloTipoNormativa import TituloTipoNormativa
from TituloOrientacion import TituloOrientacion
from Titulo import Titulo
from EstadoTitulo import EstadoTitulo
from EstadoTituloOrientacion import EstadoTituloOrientacion
from TituloOrientacionEstado import TituloOrientacionEstado
#
from TituloNacional import TituloNacional
from TituloNacionalEstado import TituloNacionalEstado
from EstadoTituloNacional import EstadoTituloNacional
#
from EstadoNormativaJurisdiccional import EstadoNormativaJurisdiccional
from TipoNormativaJurisdiccional import TipoNormativaJurisdiccional
from NormativaJurisdiccionalEstado import NormativaJurisdiccionalEstado
from NormativaJurisdiccional import NormativaJurisdiccional
from NormativaMotivoOtorgamiento import NormativaMotivoOtorgamiento
#
from EstadoNormativaNacional import EstadoNormativaNacional
from NormativaNacionalEstado import NormativaNacionalEstado
from NormativaNacional import NormativaNacional
#
from Matricula import Matricula
#
from TipoProyecto import TipoProyecto
from Proyecto import Proyecto
#
from CarreraJurisdiccional import CarreraJurisdiccional
from CarreraJurisdiccionalCohorte import CarreraJurisdiccionalCohorte
from CarreraJurisdiccionalEstado import CarreraJurisdiccionalEstado
from EstadoCarreraJurisdiccional import EstadoCarreraJurisdiccional
#
from CohorteEstablecimientoEstado import CohorteEstablecimientoEstado
from Cohorte import Cohorte
from CohorteEstablecimiento import CohorteEstablecimiento
from CohorteEstablecimientoSeguimiento import CohorteEstablecimientoSeguimiento
from EstadoCohorteEstablecimiento import EstadoCohorteEstablecimiento
#
from CohorteAnexoEstado import CohorteAnexoEstado
from CohorteAnexo import CohorteAnexo
from CohorteAnexoSeguimiento import CohorteAnexoSeguimiento
from EstadoCohorteAnexo import EstadoCohorteAnexo
#
from CohorteExtensionAulicaEstado import CohorteExtensionAulicaEstado
from CohorteExtensionAulica import CohorteExtensionAulica
from CohorteExtensionAulicaSeguimiento import CohorteExtensionAulicaSeguimiento
from EstadoCohorteExtensionAulica import EstadoCohorteExtensionAulica
#
from OpcionPedagogica import OpcionPedagogica
from TipoHora import TipoHora
from EstadoTramitePostitulo import EstadoTramitePostitulo
from Postitulo import Postitulo
#
