from ConfiguracionSolapasExtensionAulica import ConfiguracionSolapasExtensionAulica
from ConfiguracionSolapasEstablecimiento import ConfiguracionSolapasEstablecimiento
from ConfiguracionSolapasAnexo import ConfiguracionSolapasAnexo
