from TituloForm import TituloForm
from TituloFormFilters import TituloFormFilters
from TituloOrientacionForm import TituloOrientacionForm
from TituloOrientacionFormFilters import TituloOrientacionFormFilters
#
from TituloNacionalForm import TituloNacionalForm
from TituloNacionalFormFilters import TituloNacionalFormFilters
#
from NormativaJurisdiccionalForm import NormativaJurisdiccionalForm
from NormativaJurisdiccionalFormFilters import NormativaJurisdiccionalFormFilters
#
from NormativaNacionalForm import NormativaNacionalForm
from NormativaNacionalFormFilters import NormativaNacionalFormFilters
#
from MatriculaFormFilters import MatriculaFormFilters
from MatriculaForm import MatriculaForm
#
from ProyectoFormFilters import ProyectoFormFilters
from ProyectoForm import ProyectoForm
#
from CarreraJurisdiccionalFormFilters import CarreraJurisdiccionalFormFilters
from CarreraJurisdiccionalForm import CarreraJurisdiccionalForm
from CarreraJurisdiccionalDuracionForm import CarreraJurisdiccionalDuracionForm
from CarreraJurisdiccionalDatosBasicosForm import CarreraJurisdiccionalDatosBasicosForm
from CarreraJurisdiccionalOrientacionesForm import CarreraJurisdiccionalOrientacionesForm
from CarreraJurisdiccionalNormativasForm import CarreraJurisdiccionalNormativasForm
from CarreraJurisdiccionalCohorteForm import CarreraJurisdiccionalCohorteForm
from CarreraJurisdiccionalCohorteFormFilters import CarreraJurisdiccionalCohorteFormFilters
#
from CohorteForm import CohorteForm
#cohorte establecimiento
from CohorteEstablecimientoConfirmarForm import CohorteEstablecimientoConfirmarForm
from CohorteEstablecimientoSeguimientoForm import CohorteEstablecimientoSeguimientoForm
from CohorteAsignarEstablecimientosFormFilters import CohorteAsignarEstablecimientosFormFilters
from AceptarCohorteEstablecimientoFormFilters import AceptarCohorteEstablecimientoFormFilters
#cohorte anexo
from CohorteAnexoConfirmarForm import CohorteAnexoConfirmarForm
from CohorteAnexoSeguimientoForm import CohorteAnexoSeguimientoForm
from CohorteAsignarAnexosFormFilters import CohorteAsignarAnexosFormFilters
from AceptarCohorteAnexoFormFilters import AceptarCohorteAnexoFormFilters
#
#cohorte extension aulica
from CohorteAsignarExtensionesAulicasFormFilters import CohorteAsignarExtensionesAulicasFormFilters
#
from PostituloFormFilters import PostituloFormFilters
from PostituloForm import PostituloForm
#
from CarreraForm import CarreraForm
from CarreraFormFilters import CarreraFormFilters
from CarreraAsignarTitulosFormFilters import CarreraAsignarTitulosFormFilters
#
from TipoTituloForm import TipoTituloForm
from TipoTituloFormFilters import TipoTituloFormFilters
