from TituloForm import TituloForm
from TituloFormFilters import TituloFormFilters
from TituloOrientacionForm import TituloOrientacionForm
from TituloOrientacionFormFilters import TituloOrientacionFormFilters
from NormativaJurisdiccionalForm import NormativaJurisdiccionalForm
from NormativaJurisdiccionalFormFilters import NormativaJurisdiccionalFormFilters
from MatriculaFormFilters import MatriculaFormFilters
from MatriculaForm import MatriculaForm
from ProyectoFormFilters import ProyectoFormFilters
from ProyectoForm import ProyectoForm
from TituloJurisdiccionalFormFilters import TituloJurisdiccionalFormFilters
from TituloJurisdiccionalForm import TituloJurisdiccionalForm
from TituloJurisdiccionalModalidadDistanciaForm import TituloJurisdiccionalModalidadDistanciaForm
from TituloJurisdiccionalModalidadPresencialForm import TituloJurisdiccionalModalidadPresencialForm
from TituloJurisdiccionalDatosBasicosForm import TituloJurisdiccionalDatosBasicosForm
from TituloJurisdiccionalOrientacionesForm import TituloJurisdiccionalOrientacionesForm
from TituloJurisdiccionalNormativasForm import TituloJurisdiccionalNormativasForm
from TituloJurisdiccionalCohorteForm import TituloJurisdiccionalCohorteForm
from TituloJurisdiccionalCohorteFormFilters import TituloJurisdiccionalCohorteFormFilters
from CohorteForm import CohorteForm
#cohorte establecimiento
from CohorteEstablecimientoConfirmarForm import CohorteEstablecimientoConfirmarForm
from CohorteEstablecimientoSeguimientoForm import CohorteEstablecimientoSeguimientoForm
from CohorteAsignarEstablecimientosFormFilters import CohorteAsignarEstablecimientosFormFilters
from AceptarCohorteEstablecimientoFormFilters import AceptarCohorteEstablecimientoFormFilters
#cohorte anexo
from CohorteAnexoConfirmarForm import CohorteAnexoConfirmarForm
from CohorteAnexoSeguimientoForm import CohorteAnexoSeguimientoForm
from CohorteAsignarAnexosFormFilters import CohorteAsignarAnexosFormFilters
from AceptarCohorteAnexoFormFilters import AceptarCohorteAnexoFormFilters
#
#cohorte unidad de extension
from CohorteAsignarUnidadesExtensionFormFilters import CohorteAsignarUnidadesExtensionFormFilters
#
from PostituloFormFilters import PostituloFormFilters
from PostituloForm import PostituloForm
